# Generated by Django 5.2.8 on 2026-05-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_alter_partner_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
