# Generated by Django 5.2.8 on 2026-07-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='portfolio/', verbose_name='Файл изображения'),
        ),
    ]
