# Generated by Django 6.0.5 on 2026-07-17 11:37

from django.db import migrations


def load_default_settings(apps, schema_editor):
    """Загружает значения по умолчанию для настроек сайта"""
    SiteSettings = apps.get_model('my_site', 'SiteSettings')
    
    # Обновляем существующую запись или создаем новую
    settings, created = SiteSettings.objects.get_or_create(
        id=1,
        defaults={
            'business_description': 'Мы предлагаем высококачественные мебельные решения для вашего дома и офиса. Надежные материалы, современный дизайн и индивидуальный подход к каждому заказу.',
            'phone': '+7 (999) 123-45-67',
            'email': 'info@mebel-site.ru',
            'address': 'г. Москва, ул. Примерная, д. 1',
            'yandex_map_link': 'https://yandex.ru/maps'
        }
    )
    
    if not created:
        # Обновляем существующую запись
        settings.business_description = 'Мы предлагаем высококачественные мебельные решения для вашего дома и офиса. Надежные материалы, современный дизайн и индивидуальный подход к каждому заказу.'
        settings.phone = '+7 (999) 123-45-67'
        settings.email = 'info@mebel-site.ru'
        settings.address = 'г. Москва, ул. Примерная, д. 1'
        settings.yandex_map_link = 'https://yandex.ru/maps'
        settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_alter_partner_logo_alter_projectimage_image'),
    ]

    operations = [
        migrations.RunPython(load_default_settings, reverse_code=migrations.RunPython.noop),
    ]
